In [103]:
import torch as tc
import p_power as pp
import numpy as np
import matplotlib.pyplot as plt


In [104]:
phi = tc.Tensor([[0, 0, 1, 1, 1], [-2, -2, -1, 1, 1], [2, 0, 0, 0, 0], [0, 2, 0, 0, 0], [0, 0, 2, 0, 0], [0, 0, 0, -2, -2], [0, 0, 0, 2, 0], [0, 0, 0, 0, 2]])
phi_T = phi.mT
phi_G = phi_T @ phi
print(phi_G)

tensor([[ 8.,  4.,  2., -2., -2.],
        [ 4.,  8.,  2., -2., -2.],
        [ 2.,  2.,  6.,  0.,  0.],
        [-2., -2.,  0., 10.,  6.],
        [-2., -2.,  0.,  6., 10.]])


In [105]:
x_targ = tc.Tensor([[-.5], [0], [1], [.5], [-.5]])
x_start = tc.Tensor(tc.randn(5, 1))
print(x_start)

tensor([[ 0.1778],
        [ 2.0471],
        [ 0.1124],
        [-0.5795],
        [ 0.6901]])


In [106]:
phi_norm, vect = pp.p_power(phi, p=2, s_max=100, type=tc.float)
print(phi_norm)
print(vect)

tensor([[[4.3193]]])
tensor([[[-0.3884],
         [-0.3884],
         [-0.1229],
         [ 0.5845],
         [ 0.5844]]])


In [107]:
for i in range(100):
    start_norm = tc.linalg.vector_norm(x_start, ord=2, keepdims=True)
    x_start = (phi_G @ x_start) / start_norm
    x_start = pp.dual(x_start, p=2, dim=0, type=tc.float)
print(x_start) #+ 2.28892574923842)
print(start_norm)
# x_shift = x_start + 2.28892574923842
# 
# print(x_shift[-1] / - x_shift[0])

tensor([[ 0.3882],
        [ 0.3882],
        [ 0.1227],
        [-0.5846],
        [-0.5846]])
tensor([[1.]])


In [108]:
res = phi @ x_start
print(res)

res_norm = tc.linalg.vector_norm(res, ord=2, keepdims=True)

print(res_norm)

tensor([[-1.0465],
        [-2.8447],
        [ 0.7764],
        [ 0.7764],
        [ 0.2454],
        [ 2.3385],
        [-1.1692],
        [-1.1692]])
tensor([[4.3193]])


In [109]:
print( (res) / tc.min(tc.abs(res)))

tensor([[ -4.2650],
        [-11.5930],
        [  3.1640],
        [  3.1640],
        [  1.0000],
        [  9.5299],
        [ -4.7650],
        [ -4.7650]])
